server:
  port: 8090
spring:
  application:
    name: eventhub-consumer
  cloud:
    function:
      definition: consume
    stream:
      binders:
        my-default-binder:
          type: eventhub
          environment:
            spring:
              cloud:
                azure:
                  eventhub:
                    connection-string: "[connection-string]"
                    checkpoint-access-key: "[account-key]"
                    checkpoint-storage-account: "[account-name]"
      bindings:
        consume-in-0:
          destination: "[destination]"
          group: "[group]"

