server:
  port: 8090
spring:
  application:
    name: eventhub-consumer
  cloud:
    function:
      definition: consume
    stream:
      eventhubs:
        bindings:
          consume-in-0:
            consumer:
              track-last-enqueued-event-properties: true
      binders:
        my-default-binder:
          type: eventhubs
          environment:
            spring:
              cloud:
                azure:
                  eventhubs:
                    connection-string: "[connection-string]"
                    processor:
                      checkpoint-store:
                        create-container-if-not-exists: true
                        container-name: "[container-name]"
                        account-name: "[account-name]"
                        account-key: "[account-key]"
      bindings:
        consume-in-0:
          destination: "[destination]"
          group: "[group]"






