server:
  port: 8095
spring:
  application:
    name: eventhub-transformer-dlq
  cloud:
    function:
      definition: transform;dlq
    stream:
      eventhub:
        bindings:
          transform-in-0:
            consumer:
              checkpoint:
                mode: MANUAL
      binders:
        my-default-binder:
          type: eventhub
          environment:
            spring:
              cloud:
                azure:
                  eventhub:
                    connection-string: "[connection-string]"
                    checkpoint-access-key: "[account-key]"
                    checkpoint-storage-account: "[account-name]"
      bindings:
        transform-in-0:
          destination: "[destination]"
          group: "[group]"
        transform-out-0:
          destination: "[destination]"
        dlq-out-0:
          destination: "[destination]"
