server:
  port: 8092
spring:
  application:
    name: eventhub-batch-consumer
  cloud:
    function:
      definition: consume
    stream:
      eventhubs:
        bindings:
          consume-in-0:
            consumer:
              track-last-enqueued-event-properties: true
              batch:
                max-size: 100
                max-wait-time: 1500ms
              checkpoint:
                mode: BATCH
      binders:
        my-default-binder:
          type: eventhubs
          default-candidate: true
          environment:
            spring:
              cloud:
                azure:
                  eventhubs:
                    connection-string: "[connection-string]"
                    processor:
                      checkpoint-store:
                        create-container-if-not-exists: true
                        container-name: "[container-name]"
                        account-name: "[account-name]"
                        account-key: "[account-key]"
      bindings:
        consume-in-0:
          destination: "[destination]"
          group: "[group]"
          consumer:
            batch-mode: true
